extend type LeagueEntry {
  """
  ✨ Implicit foreign key field based on `LeagueEntry`.`entry`. It must match the value of `Entry`.`entryId`. See `@ref` for how to customize it.
  """
  entryEntryId: Int! @fdc_generated(from: "LeagueEntry.entry", purpose: IMPLICIT_REF_FIELD)
}
extend type MatchPick {
  """
  ✨ Implicit foreign key field based on `MatchPick`.`entry`. It must match the value of `Entry`.`entryId`. See `@ref` for how to customize it.
  """
  entryEntryId: Int! @fdc_generated(from: "MatchPick.entry", purpose: IMPLICIT_REF_FIELD)
}
extend type Participant {
  """
  ✨ Implicit foreign key field based on `Participant`.`entry`. It must match the value of `Entry`.`entryId`. See `@ref` for how to customize it.
  """
  entryEntryId: Int! @fdc_generated(from: "Participant.entry", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Participant`.`user`. It must match the value of `User`.`uid`. See `@ref` for how to customize it.
  """
  userUid: String @fdc_generated(from: "Participant.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Pick {
  """
  ✨ Implicit foreign key field based on `Pick`.`entry`. It must match the value of `Entry`.`entryId`. See `@ref` for how to customize it.
  """
  entryEntryId: Int! @fdc_generated(from: "Pick.entry", purpose: IMPLICIT_REF_FIELD)
}
extend type TournamentEntry {
  """
  ✨ Implicit foreign key field based on `TournamentEntry`.`entry`. It must match the value of `Entry`.`entryId`. See `@ref` for how to customize it.
  """
  entryEntryId: Int! @fdc_generated(from: "TournamentEntry.entry", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `TournamentEntry`.`user`. It must match the value of `User`.`uid`. See `@ref` for how to customize it.
  """
  userUid: String @fdc_generated(from: "TournamentEntry.user", purpose: IMPLICIT_REF_FIELD)
}
