extend type Mutation {
  """
  ✨ Insert a single `EmailQueue` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  emailQueue_insert(
    """
    Data object to insert into the table.
    """
    data: EmailQueue_Data!
  ): EmailQueue_KeyOutput! @fdc_generated(from: "EmailQueue", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Entry` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  entry_insert(
    """
    Data object to insert into the table.
    """
    data: Entry_Data!
  ): Entry_KeyOutput! @fdc_generated(from: "Entry", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Event` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  event_insert(
    """
    Data object to insert into the table.
    """
    data: Event_Data!
  ): Event_KeyOutput! @fdc_generated(from: "Event", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `League` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  league_insert(
    """
    Data object to insert into the table.
    """
    data: League_Data!
  ): League_KeyOutput! @fdc_generated(from: "League", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `LeagueEntry` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  leagueEntry_insert(
    """
    Data object to insert into the table.
    """
    data: LeagueEntry_Data!
  ): LeagueEntry_KeyOutput! @fdc_generated(from: "LeagueEntry", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Match` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  match_insert(
    """
    Data object to insert into the table.
    """
    data: Match_Data!
  ): Match_KeyOutput! @fdc_generated(from: "Match", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `MatchPick` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  matchPick_insert(
    """
    Data object to insert into the table.
    """
    data: MatchPick_Data!
  ): MatchPick_KeyOutput! @fdc_generated(from: "MatchPick", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Participant` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  participant_insert(
    """
    Data object to insert into the table.
    """
    data: Participant_Data!
  ): Participant_KeyOutput! @fdc_generated(from: "Participant", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ParticipantLeague` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  participantLeague_insert(
    """
    Data object to insert into the table.
    """
    data: ParticipantLeague_Data!
  ): ParticipantLeague_KeyOutput! @fdc_generated(from: "ParticipantLeague", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Pick` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  pick_insert(
    """
    Data object to insert into the table.
    """
    data: Pick_Data!
  ): Pick_KeyOutput! @fdc_generated(from: "Pick", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Round` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  round_insert(
    """
    Data object to insert into the table.
    """
    data: Round_Data!
  ): Round_KeyOutput! @fdc_generated(from: "Round", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Tournament` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  tournament_insert(
    """
    Data object to insert into the table.
    """
    data: Tournament_Data!
  ): Tournament_KeyOutput! @fdc_generated(from: "Tournament", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `EmailQueue` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  emailQueue_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [EmailQueue_Data!]!
  ): [EmailQueue_KeyOutput!]! @fdc_generated(from: "EmailQueue", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Entry` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  entry_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Entry_Data!]!
  ): [Entry_KeyOutput!]! @fdc_generated(from: "Entry", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Event` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  event_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Event_Data!]!
  ): [Event_KeyOutput!]! @fdc_generated(from: "Event", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `League` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  league_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [League_Data!]!
  ): [League_KeyOutput!]! @fdc_generated(from: "League", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `LeagueEntry` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  leagueEntry_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [LeagueEntry_Data!]!
  ): [LeagueEntry_KeyOutput!]! @fdc_generated(from: "LeagueEntry", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Match` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  match_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Match_Data!]!
  ): [Match_KeyOutput!]! @fdc_generated(from: "Match", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `MatchPick` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  matchPick_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [MatchPick_Data!]!
  ): [MatchPick_KeyOutput!]! @fdc_generated(from: "MatchPick", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Participant` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  participant_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Participant_Data!]!
  ): [Participant_KeyOutput!]! @fdc_generated(from: "Participant", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ParticipantLeague` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  participantLeague_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ParticipantLeague_Data!]!
  ): [ParticipantLeague_KeyOutput!]! @fdc_generated(from: "ParticipantLeague", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Pick` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  pick_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Pick_Data!]!
  ): [Pick_KeyOutput!]! @fdc_generated(from: "Pick", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Round` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  round_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Round_Data!]!
  ): [Round_KeyOutput!]! @fdc_generated(from: "Round", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Tournament` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  tournament_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Tournament_Data!]!
  ): [Tournament_KeyOutput!]! @fdc_generated(from: "Tournament", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `EmailQueue` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `EmailQueue`.
  """
  emailQueue_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: EmailQueue_Data!
  ): EmailQueue_KeyOutput! @fdc_generated(from: "EmailQueue", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Entry` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Entry`.
  """
  entry_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Entry_Data!
  ): Entry_KeyOutput! @fdc_generated(from: "Entry", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Event` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Event`.
  """
  event_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Event_Data!
  ): Event_KeyOutput! @fdc_generated(from: "Event", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `League` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `League`.
  """
  league_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: League_Data!
  ): League_KeyOutput! @fdc_generated(from: "League", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `LeagueEntry` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LeagueEntry`.
  """
  leagueEntry_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: LeagueEntry_Data!
  ): LeagueEntry_KeyOutput! @fdc_generated(from: "LeagueEntry", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Match` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Match`.
  """
  match_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Match_Data!
  ): Match_KeyOutput! @fdc_generated(from: "Match", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `MatchPick` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MatchPick`.
  """
  matchPick_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: MatchPick_Data!
  ): MatchPick_KeyOutput! @fdc_generated(from: "MatchPick", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Participant` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Participant`.
  """
  participant_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Participant_Data!
  ): Participant_KeyOutput! @fdc_generated(from: "Participant", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ParticipantLeague` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ParticipantLeague`.
  """
  participantLeague_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ParticipantLeague_Data!
  ): ParticipantLeague_KeyOutput! @fdc_generated(from: "ParticipantLeague", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Pick` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Pick`.
  """
  pick_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Pick_Data!
  ): Pick_KeyOutput! @fdc_generated(from: "Pick", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Round` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Round`.
  """
  round_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Round_Data!
  ): Round_KeyOutput! @fdc_generated(from: "Round", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Tournament` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Tournament`.
  """
  tournament_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Tournament_Data!
  ): Tournament_KeyOutput! @fdc_generated(from: "Tournament", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `EmailQueue` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `EmailQueue`.
  """
  emailQueue_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [EmailQueue_Data!]!
  ): [EmailQueue_KeyOutput!]! @fdc_generated(from: "EmailQueue", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Entry` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Entry`.
  """
  entry_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Entry_Data!]!
  ): [Entry_KeyOutput!]! @fdc_generated(from: "Entry", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Event` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Event`.
  """
  event_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Event_Data!]!
  ): [Event_KeyOutput!]! @fdc_generated(from: "Event", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `League` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `League`.
  """
  league_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [League_Data!]!
  ): [League_KeyOutput!]! @fdc_generated(from: "League", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `LeagueEntry` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LeagueEntry`.
  """
  leagueEntry_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [LeagueEntry_Data!]!
  ): [LeagueEntry_KeyOutput!]! @fdc_generated(from: "LeagueEntry", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Match` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Match`.
  """
  match_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Match_Data!]!
  ): [Match_KeyOutput!]! @fdc_generated(from: "Match", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `MatchPick` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MatchPick`.
  """
  matchPick_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [MatchPick_Data!]!
  ): [MatchPick_KeyOutput!]! @fdc_generated(from: "MatchPick", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Participant` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Participant`.
  """
  participant_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Participant_Data!]!
  ): [Participant_KeyOutput!]! @fdc_generated(from: "Participant", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ParticipantLeague` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ParticipantLeague`.
  """
  participantLeague_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ParticipantLeague_Data!]!
  ): [ParticipantLeague_KeyOutput!]! @fdc_generated(from: "ParticipantLeague", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Pick` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Pick`.
  """
  pick_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Pick_Data!]!
  ): [Pick_KeyOutput!]! @fdc_generated(from: "Pick", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Round` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Round`.
  """
  round_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Round_Data!]!
  ): [Round_KeyOutput!]! @fdc_generated(from: "Round", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Tournament` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Tournament`.
  """
  tournament_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Tournament_Data!]!
  ): [Tournament_KeyOutput!]! @fdc_generated(from: "Tournament", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `EmailQueue` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `EmailQueue` or `null` if not found.
  """
  emailQueue_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: EmailQueue_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EmailQueue_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: EmailQueue_Data!
  ): EmailQueue_KeyOutput @fdc_generated(from: "EmailQueue", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Entry` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Entry` or `null` if not found.
  """
  entry_update(
    """
    The key used to identify the object.
    """
    key: Entry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Entry_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Entry_Data!
  ): Entry_KeyOutput @fdc_generated(from: "Entry", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Event` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Event` or `null` if not found.
  """
  event_update(
    """
    The key used to identify the object.
    """
    key: Event_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Event_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Event_Data!
  ): Event_KeyOutput @fdc_generated(from: "Event", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `League` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `League` or `null` if not found.
  """
  league_update(
    """
    The key used to identify the object.
    """
    key: League_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: League_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: League_Data!
  ): League_KeyOutput @fdc_generated(from: "League", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `LeagueEntry` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `LeagueEntry` or `null` if not found.
  """
  leagueEntry_update(
    """
    The key used to identify the object.
    """
    key: LeagueEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LeagueEntry_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: LeagueEntry_Data!
  ): LeagueEntry_KeyOutput @fdc_generated(from: "LeagueEntry", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Match` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Match` or `null` if not found.
  """
  match_update(
    """
    The key used to identify the object.
    """
    key: Match_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Match_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Match_Data!
  ): Match_KeyOutput @fdc_generated(from: "Match", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `MatchPick` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `MatchPick` or `null` if not found.
  """
  matchPick_update(
    """
    The key used to identify the object.
    """
    key: MatchPick_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MatchPick_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: MatchPick_Data!
  ): MatchPick_KeyOutput @fdc_generated(from: "MatchPick", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Participant` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Participant` or `null` if not found.
  """
  participant_update(
    """
    The key used to identify the object.
    """
    key: Participant_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Participant_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Participant_Data!
  ): Participant_KeyOutput @fdc_generated(from: "Participant", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ParticipantLeague` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ParticipantLeague` or `null` if not found.
  """
  participantLeague_update(
    """
    The key used to identify the object.
    """
    key: ParticipantLeague_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ParticipantLeague_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ParticipantLeague_Data!
  ): ParticipantLeague_KeyOutput @fdc_generated(from: "ParticipantLeague", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Pick` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Pick` or `null` if not found.
  """
  pick_update(
    """
    The key used to identify the object.
    """
    key: Pick_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Pick_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Pick_Data!
  ): Pick_KeyOutput @fdc_generated(from: "Pick", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Round` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Round` or `null` if not found.
  """
  round_update(
    """
    The key used to identify the object.
    """
    key: Round_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Round_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Round_Data!
  ): Round_KeyOutput @fdc_generated(from: "Round", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Tournament` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Tournament` or `null` if not found.
  """
  tournament_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Tournament_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Tournament_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Tournament_Data!
  ): Tournament_KeyOutput @fdc_generated(from: "Tournament", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `EmailQueue` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  emailQueue_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: EmailQueue_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: EmailQueue_Data!
  ): Int! @fdc_generated(from: "EmailQueue", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Entry` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  entry_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Entry_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Entry_Data!
  ): Int! @fdc_generated(from: "Entry", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Event` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  event_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Event_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Event_Data!
  ): Int! @fdc_generated(from: "Event", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `League` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  league_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: League_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: League_Data!
  ): Int! @fdc_generated(from: "League", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `LeagueEntry` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  leagueEntry_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: LeagueEntry_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: LeagueEntry_Data!
  ): Int! @fdc_generated(from: "LeagueEntry", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Match` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  match_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Match_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Match_Data!
  ): Int! @fdc_generated(from: "Match", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `MatchPick` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  matchPick_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: MatchPick_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: MatchPick_Data!
  ): Int! @fdc_generated(from: "MatchPick", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Participant` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  participant_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Participant_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Participant_Data!
  ): Int! @fdc_generated(from: "Participant", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ParticipantLeague` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  participantLeague_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ParticipantLeague_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ParticipantLeague_Data!
  ): Int! @fdc_generated(from: "ParticipantLeague", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Pick` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  pick_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Pick_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Pick_Data!
  ): Int! @fdc_generated(from: "Pick", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Round` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  round_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Round_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Round_Data!
  ): Int! @fdc_generated(from: "Round", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Tournament` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  tournament_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Tournament_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Tournament_Data!
  ): Int! @fdc_generated(from: "Tournament", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `EmailQueue` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  emailQueue_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: EmailQueue_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EmailQueue_FirstRow
  ): EmailQueue_KeyOutput @fdc_generated(from: "EmailQueue", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Entry` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  entry_delete(
    """
    The key used to identify the object.
    """
    key: Entry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Entry_FirstRow
  ): Entry_KeyOutput @fdc_generated(from: "Entry", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Event` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  event_delete(
    """
    The key used to identify the object.
    """
    key: Event_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Event_FirstRow
  ): Event_KeyOutput @fdc_generated(from: "Event", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `League` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  league_delete(
    """
    The key used to identify the object.
    """
    key: League_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: League_FirstRow
  ): League_KeyOutput @fdc_generated(from: "League", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `LeagueEntry` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  leagueEntry_delete(
    """
    The key used to identify the object.
    """
    key: LeagueEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LeagueEntry_FirstRow
  ): LeagueEntry_KeyOutput @fdc_generated(from: "LeagueEntry", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Match` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  match_delete(
    """
    The key used to identify the object.
    """
    key: Match_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Match_FirstRow
  ): Match_KeyOutput @fdc_generated(from: "Match", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `MatchPick` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  matchPick_delete(
    """
    The key used to identify the object.
    """
    key: MatchPick_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MatchPick_FirstRow
  ): MatchPick_KeyOutput @fdc_generated(from: "MatchPick", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Participant` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  participant_delete(
    """
    The key used to identify the object.
    """
    key: Participant_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Participant_FirstRow
  ): Participant_KeyOutput @fdc_generated(from: "Participant", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ParticipantLeague` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  participantLeague_delete(
    """
    The key used to identify the object.
    """
    key: ParticipantLeague_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ParticipantLeague_FirstRow
  ): ParticipantLeague_KeyOutput @fdc_generated(from: "ParticipantLeague", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Pick` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  pick_delete(
    """
    The key used to identify the object.
    """
    key: Pick_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Pick_FirstRow
  ): Pick_KeyOutput @fdc_generated(from: "Pick", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Round` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  round_delete(
    """
    The key used to identify the object.
    """
    key: Round_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Round_FirstRow
  ): Round_KeyOutput @fdc_generated(from: "Round", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Tournament` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  tournament_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Tournament_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Tournament_FirstRow
  ): Tournament_KeyOutput @fdc_generated(from: "Tournament", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `EmailQueue` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  emailQueue_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: EmailQueue_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "EmailQueue", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Entry` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  entry_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Entry_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Entry", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Event` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  event_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Event_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Event", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `League` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  league_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: League_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "League", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `LeagueEntry` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  leagueEntry_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: LeagueEntry_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "LeagueEntry", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Match` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  match_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Match_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Match", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `MatchPick` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  matchPick_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: MatchPick_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "MatchPick", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Participant` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  participant_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Participant_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Participant", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ParticipantLeague` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  participantLeague_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ParticipantLeague_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ParticipantLeague", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Pick` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  pick_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Pick_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Pick", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Round` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  round_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Round_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Round", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Tournament` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  tournament_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Tournament_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Tournament", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
